package Entities.Space;

public enum SpaceType {

    OFFICE_SPACE, TEACHING_SPACE, LABORATORY_SPACE, ANCILLARY_SPACE, GENERAL_SPACE, INFORMATION_SERVICE_LIBRARY, STUDENT_ACCOMODATION, NON_USABLE;

}
